### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by seyioyemade** [Rimuru-Tempest-26/Portfolio#11]
## Peer-to-peer code review

- I think the paragraph in the 'contact me' section should have more contrast.
- It would be better if the menu font-size can be increased.
- I would suggest you separate the font sizes of different elements in the project section to improve accessibility.
- I think there should be more top-margin added to the button in the project section.

**Comment by Phone-Khaing-Hein** [comment]
Thanks for advising me for better. I will fix that.
